### ISSUE TITLE
[Feature Request] Retain commit messages

### ISSUE THREAD

**Issue by wjaspers** [fidian/git-started#19]
Other users have mentioned that the hooks' process of unstaging changes causes the commit message to be lost. Based on the changeset, could we generate a temporary file which retains the commit message and re-uses it?
I haven't looked at this in depth yet, just tossing an idea around.

**Comment by fidian** [comment]
How can I replicate this behavior that you are describing?  I would like to better understand the issues you're facing.

**Comment by wjaspers** [comment]
Huh, come to think of it, this might be an issue specific to the use of SublimeText as a commit message editor. A coworker brought this concern up, but I cannot recall having the same experience when creating a commit message through the git CLI or its configured CLI editor (in my case, vim).

For instance, lets assume I have Fabien's PHP Code standards fixer installed globally.
`composer.phar global require fabpot/php-cs-fixer`

`git clone https://github.com/fidian/git-started.git project
cd project
./util/bin/setup-repository
echo "<?php class Test {\n\tprotected $property = 'test';\n}" > Test.php
git add Test.php
git commit
`

The staged file will be pretty printed, and the commit cancelled.
The file's unstaged changes will be the pretty printed contents.
I can attempt to commit again, in which case, the commit message must be re-typed (and why this now looks like an editor-specific problem).

Sorry for the confusion.

**Comment by fidian** [comment]
Shall we consider this issue resolved for now, with the caveat that if it turns out to be a real problem with the hooks then you'll be back to let me know about it?

**Comment by wjaspers** [comment]
Indeed we shall, and I will certainly do that.
